# Generated by Django 5.2 on 2025-07-12 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_profile_height_alter_profile_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cover_photo',
            field=models.ImageField(blank=True, default='blank_profile_picture.png', upload_to='cover_photos/'),
        ),
    ]
