# Generated by Django 5.2 on 2025-07-14 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_profile_friends'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_visits',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
