# Generated by Django 5.2 on 2025-07-19 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_conversation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Conversation',
        ),
    ]
